# Generated by Django 3.2.5 on 2021-07-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210716_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_alter', models.ManyToManyField(related_name='alternative_products', to='Product.Product', verbose_name='Alternatives')),
                ('product_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_prodcut', to='Product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Product Alternatives',
            },
        ),
    ]
