# Generated by Django 3.2.5 on 2021-07-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210718_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCAlternatives', models.ManyToManyField(related_name='accessories_products', to='Product.Product', verbose_name='Accessories')),
                ('ACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainaccessory_prodcut', to='Product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
