# Generated by Django 3.2.5 on 2021-08-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountprice',
            field=models.FloatField(default=0, verbose_name='الخصم علي المنتج'),
            preserve_default=False,
        ),
    ]
