# Generated by Django 3.2.5 on 2021-08-30 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Customer_image', verbose_name='الصوره')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='الدوله')),
                ('address', models.CharField(max_length=100, verbose_name='العنوان')),
                ('join_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ الانضمام')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
